#!/usr/bin/env python

from BaseHTTPServer import BaseHTTPRequestHandler, HTTPServer
from sys import argv
from urlparse import urlparse, parse_qs
from subprocess import call

class EditorDaemonHandler(BaseHTTPRequestHandler):
  def _set_headers(self):
    self.send_response(200)
    self.send_header('Content-type', 'text/html')
    self.end_headers()

  def do_GET(self):
    parsed = urlparse(self.path)
    qs = parse_qs(parsed.query)
    if 'n' in qs:
      if len(qs['n']) == 1:
        n = qs['n'][0]
        n = n[1:-5] + ".md"
        print(n)
        call(['gvim', n])   
        self._set_headers()
        self.wfile.write('<html><body><h1>It works!</h1></body></html>')

def run(server_class=HTTPServer, handler_class=EditorDaemonHandler, port=80):
  server_address = ('127.0.0.1', port)
  httpd = server_class(server_address, handler_class)
  httpd.serve_forever()

if __name__ == '__main__':
  if len(argv) == 2:
    run(port=int(argv[1]))
  else:
    run()
